update

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -13,10 +13,19 @@ if [[ $SSH_CONNECTION != "" ]]; then
   PS1="${Color}SSH${RCol} "
 fi
 
-PS1+='\[\e[0;96m\]\u\[\e[0m\]@\[\e[0;92m\]\H\[\e[0m\]:\[\e[0;93m\]$(git branch 2>/dev/null | grep '"'"'^*'"'"' | colrm 1 2) \[\e[0m\]\w\n\[\e[0m\]\$ \[\e[0m\]'
+function print_code_if_error () {
+  code=$?
+  
+  if [[ $code != 0 ]]; then
+    echo
+    printf "\033[0;31m[error: $code]\033[0m\n";
+    printf "\v"
+  fi
+}
+
+PS1+='$(print_code_if_error)\[\e[0;96m\]\u\[\e[0m\]@\[\e[0;92m\]\H\[\e[0m\]:\[\e[0;93m\]$(git branch 2>/dev/null | grep '"'"'^*'"'"' | colrm 1 2) \[\e[0m\]\w\n\[\e[0m\]\$ \[\e[0m\]'
 
 export PS1
-
 
 export PATH="$HOME/.local/bin:$HOME/go/bin:/home/zach/.cargo/bin:$PATH:$HOME/devel/klong"
 export CPATH="$HOME/.local/include:$CPATH"
